version: "3"

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./conf:/etc/letsencrypt
      - ./www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
